### ISSUE TITLE
ReMaDDer fuzzy data matching software

### ISSUE THREAD

**Issue by matalab** [J535D165/data-matching-software#1]
Please include ReMaDDer software (http://remaddersoft.wixsite.com/remadder) into this list of free fuzzy data matching programs.
ReMaDDer is unsupervised free fuzzy data matching software with user-friendly GUI front-end.  ReMaDDer is capable to perform fully automatic fuzzy record matching without human expert intervention, while attaining accuracy of human clerical review. This is accomplished by utilizing various advanced machine learning techniques and approaches.

**Comment by J535D165** [comment]
Nice find. 

Interested in doing a PR? (Then you are one of the contributors)

**Comment by J535D165** [comment]
Can you tell me why the internet connection is required?

**Comment by matalab** [comment]
Because, while projects are defined and stored locally, fuzzy match processing is performed on back-end Postgresql server.
