### ISSUE TITLE
Has anyone tested RLTK: Record Linkage ToolKit ?

### ISSUE THREAD

**Issue by JonnasSeaworth2015** [J535D165/data-matching-software#5]
I have just started looking for open-source software that deals with Data Matching and stumbled on this project. It's very helpful. As I intend to use Python I found two libraries that look  very good but as newbie I'm not sure of which one would fit better my needs. One of them is The Python Record Linkage Toolkit, that is covered in this overview. The other one is RLTK - The Record Linkage ToolKit ( https://github.com/usc-isi-i2/rltk     ).  Has anyone used the second one ? Can you include it in this overview ?

**Comment by J535D165** [comment]
Thanks you for sharing this package. I don't have any experience with it. I will add it to the list.
