### ISSUE TITLE
You can do supervised training with dedupe

### ISSUE THREAD

**Issue by fgregg** [J535D165/data-matching-software#6]
Hi, 

Thanks for pulling this resource together. I'm sure it will help many people orient to the options.

I noticed that you indicate that dedupe cannot do supervised learning. It can. Here are two relevant methods:

- https://docs.dedupe.io/en/latest/API-documentation.html#RecordLink.markPairs
- https://docs.dedupe.io/en/latest/API-documentation.html#Dedupe.readTraining

**Comment by J535D165** [comment]
Thanks for the information and good to know. I will update it soon (or you can do a PR).

**Comment by J535D165** [comment]
Closed by #7
